os-ext-testing: Enable dom0 logs collecting
citrix-openstack/os-ext-testing pull request #10
Opened 2017-06-23 03:35 UTC by naichuans

CI should save some Dom0 log files which may be useful for issue
analysis
Initial needed dom0 log files:
/var/log:
messages*
SMlog*
xensource.log
user.log*

Change-Id: I196bb885c46ee403f2cd000c33df994be5810466

2017-06-23 03:46 UTC, Annie-XIE commented on jenkins/jobs/macros-common.yaml
> +          mkdir -pm 777 logs/domzero_logs
There is no need for 777 mode?

2017-06-23 03:47 UTC, naichuans commented on jenkins/jobs/macros-common.yaml
> +          mkdir -pm 777 logs/domzero_logs
will modify it

2017-06-23 10:00 UTC, BobBall commented on jenkins/jobs/jobs.yaml
> +
I don't want to remove these, but any formatting changes should really be separated out into an isolated change in future please.

2017-06-23 10:02 UTC, BobBall commented on jenkins/jobs/macros-common.yaml
> +          mkdir -pm 777 logs/domzero_logs
We might need 777; it depends who needs to list files in the directory.  Note that the execute permission is needed for directories to list files within them.

2017-06-23 10:02 UTC, BobBall approved these changes
I think that this is good to merge, but given Huan's comments I won't merge it yet.  Huan if you're happy please merge.

2017-06-23 10:17 UTC, naichuans commented on jenkins/jobs/jobs.yaml
> +
Hi, Bob, sorry about the formatting changes. I will take care of such kind of things next time.

2017-06-25 12:11 UTC, jianghuaw requested changes

2017-06-25 12:11 UTC, jianghuaw commented on jenkins/jobs/macros-common.yaml
> +          sudo -u domzero scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{dom0_ip}:/var/log/messages /home/domzero/logs/
As we talked, messages is not the only logs need to be copied. Please refer to the log list in the ticket. And need take account of the rotated logs e.g. messages.1

2017-06-26 05:40 UTC, jianghuaw requested changes
See inline comments.

2017-06-26 05:40 UTC, jianghuaw commented on jenkins/jobs/macros-common.yaml
> +          sudo -u domzero scp -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@{dom0_ip}:/var/log/\{messages*,user.log*,SMlog*,xensource.log\} /home/domzero/logs/
xensource.log =>xensource.log*

2017-06-26 05:40 UTC, jianghuaw commented on jenkins/jobs/macros-common.yaml
> +          sudo -u domzero chmod -R 644 ~domzero/logs
I guess this will fail. You shouldn't remove the executable bit for a directory, otherwise it's not able to enter this directory.

2017-06-26 07:18 UTC, Annie-XIE commented on jenkins/jobs/macros-common.yaml
> +          mkdir -pm 777 logs/domzero_logs
I see, sorry that I don't know which is the correct mode, just though 755 is enough, so ignore my comment here

2017-06-26 07:38 UTC, naichuans commented on jenkins/jobs/macros-common.yaml
> +          mkdir -pm 777 logs/domzero_logs
Will change to 755 and have a test

2017-06-26 07:57 UTC, jianghuaw approved these changes
This looks good now. Just waiting for the CI verification job finished. Then we can merge this change and apply it to the external CI.

2017-06-27 05:24 UTC, merged